version: '3'

services:
  mrm-backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    environment:
      - DATABASE_URL=
      - NODE_ENV=development
      - COGNITO_USERPOOL=""
    ports:
      - '8000:8000'
    container_name: mrm-backend
    networks:
      - mrm-app

networks:
  mrm-app:
    driver: bridge
