-- AlterTable
ALTER TABLE `Well` MODIFY `voltage` INTEGER NULL,
    MODIFY `totalDepth` INTEGER NULL,
    MODIFY `sieveDepth` INTEGER NULL,
    MODIFY `staticLevel` INTEGER NULL,
    MODIFY `dynamicLevel` INTEGER NULL,
    MODIFY `deliveryDate` DATETIME(3) NULL,
    MODIFY `sedimentaryDepth` INTEGER NULL,
    MODIFY `price` INTEGER NULL,
    MODIFY `distric` VARCHAR(191) NULL,
    MODIFY `cep` VARCHAR(191) NULL,
    MODIFY `street` VARCHAR(191) NULL,
    MODIFY `number` VARCHAR(191) NULL,
    MODIFY `longitude` VARCHAR(191) NULL,
    MODIFY `latitude` VARCHAR(191) NULL,
    MODIFY `mapLink` VARCHAR(191) NULL;
