export const wellDefaultValues = {
  cep: '',
  mapLink: '',
  city: {
    id: '',
    name: '',
    uf: '',
  },
  cityId: '',
  client: {
    contactName: '',
    contactPhone: '',
    cpfCnpj: '',
    id: '',
    name: '',
    tenantId: '',
  },
  clientName: '',
  deliveryDate: '',
  distric: '',
  dynamicLevel: 0,
  latitude: '',
  longitude: '',
  number: '',
  proposalId: '',
  proposalServiceId: '',
  sedimentaryDepth: 0,
  sieveDepth: 0,
  staticLevel: 0,
  street: '',
  id: '',
  totalDepth: 0,
  voltage: 'V110',
  zipcode: '',
};
